export const countries = [
  {
    name: "USA",
    code: "us",
    flag: "\uD83C\uDDFA\uD83C\uDDF8",
    tagline: "High salaries - tech opportunities",
    benefit: "Best for STEM, strong job market, global exposure.",
    highlights: ["$80k+ salary", "OPT available", "Top universities"],
    outcome: "Best ROI for STEM",
  },
  {
    name: "Canada",
    code: "ca",
    flag: "\uD83C\uDDE8\uD83C\uDDE6",
    tagline: "PR friendly - safe choice",
    benefit: "Easy PR pathways, high quality of life.",
    highlights: ["PR pathways", "Affordable", "Part-time work"],
    outcome: "Balanced long-term plan",
  },
  {
    name: "UK",
    code: "gb",
    flag: "\uD83C\uDDEC\uD83C\uDDE7",
    tagline: "1-year masters - fast track",
    benefit: "Shorter degrees, globally recognized universities.",
    highlights: ["1-year courses", "PSW visa", "Top colleges"],
    outcome: "Fastest study path",
  },
  {
    name: "Australia",
    code: "au",
    flag: "\uD83C\uDDE6\uD83C\uDDFA",
    tagline: "Work-life balance - PR options",
    benefit: "Strong job market with good lifestyle.",
    highlights: ["PR options", "High demand jobs", "Good pay"],
    outcome: "Lifestyle plus opportunity",
  },
  {
    name: "Germany",
    code: "de",
    flag: "\uD83C\uDDE9\uD83C\uDDEA",
    tagline: "Low fees - strong engineering",
    benefit: "Affordable education with strong industry links.",
    highlights: ["Low tuition", "EU exposure", "Engineering hub"],
    outcome: "Affordable quality",
  },
];
